info:
    name: Admin Update Hash Values
    type: http
    seq: 177
http:
    method: GET
    url: '{{baseUrl}}/admin/updateHashValues/:alg'
    params:
        - name: alg
          value: '{{alg}}'
          type: path
        - name: num
          value: "0"
          type: query
    auth: inherit
