name: Conversion Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert-openapi-to-bruno:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
         
    - name: Read the baseUrl from dv.txt
      id: read_base_url
      run: echo "BASE_URL=$(cat dv.txt)" >> $GITHUB_ENV
    
    - name: Get the Latest openapi spec from the Dataverse installation
      run: curl -L  ${{ env.BASE_URL }}/openapi -o config.yaml

    - name: Merge custom_config.yaml into config.yaml
      run: |
        yq -i '. * load("custom_config.yaml") | .components = (.components * load("custom_config.yaml").components)' config.yaml

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'

    - name: Install the vacuum CLI
      run: npm i -g @quobix/vacuum
    
    - name: Convert OpenAPI spec to Openapi collection
      env:
        NODE_OPTIONS: --max-old-space-size=7168
      run: vacuum open-collection config.yaml ./dataverse_endpoints/ --name "Dataverse API" -q
    
    - name: Commit and push openapi collection
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Update Openapi collection from OpenAPI spec from ${{ env.BASE_URL }}/openapi [ci]
        file_pattern: '. :!dataverse_endpoints/environments/*'