name: Conversion Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert-openapi-to-bruno:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
         
    - name: Read the baseUrl from baseUrl.txt
      id: read_base_url
      run: echo "BASE_URL=$(cat baseUrl.txt)" >> $GITHUB_ENV
    
    - name: Get the Latest openapi spec from the Dataverse installation
      env:
        OPENAPI_URL: ${{ env.BASE_URL }}/openapi
      run: curl -L  ${{ env.OPENAPI_URL }} -o config.yaml

    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: '24'
    
    - name: Install Bruno CLI
      run: npm install -g @usebruno/cli
    
    - name: Convert OpenAPI spec to Bruno collection
      env:
        NODE_OPTIONS: --max-old-space-size=7168
      run: bru import openapi -s config.yaml -o ./dataverse
    
    - name: Commit and push Bruno collection
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Update Bruno collection from OpenAPI spec
        file_pattern: ./dataverse/**